// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmg2T_kDdGIxRKUVcUJdzaoh25r9IQ_b4',
    appId: '1:120033213805:web:18fe9638abd854e7a1ae64',
    messagingSenderId: '120033213805',
    projectId: 'right-e77c8',
    authDomain: 'right-e77c8.firebaseapp.com',
    storageBucket: 'right-e77c8.appspot.com',
    measurementId: 'G-0FF42HXMH0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK7FbQ2fRO-UfEO9IXEPSC_4dDXzjjH0s',
    appId: '1:120033213805:android:c5e7f14357a18c58a1ae64',
    messagingSenderId: '120033213805',
    projectId: 'right-e77c8',
    storageBucket: 'right-e77c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN-r7IRix2jKEPV6FJxL_L5HI5K5Fj7Ds',
    appId: '1:120033213805:ios:7e7b70b6878495c9a1ae64',
    messagingSenderId: '120033213805',
    projectId: 'right-e77c8',
    storageBucket: 'right-e77c8.appspot.com',
    iosBundleId: 'com.example.rbsAndroid',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDN-r7IRix2jKEPV6FJxL_L5HI5K5Fj7Ds',
    appId: '1:120033213805:ios:308f21d7141fe3a1a1ae64',
    messagingSenderId: '120033213805',
    projectId: 'right-e77c8',
    storageBucket: 'right-e77c8.appspot.com',
    iosBundleId: 'com.example.rbsAndroid.RunnerTests',
  );
}
